server:
  port: 8095


spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop   # SessionFactory 실행될 때 Drop, Create, Alter . 종료될 때 Drop
    properties:
      hibernate:
#        콘솔창 sql
        format_sql: true
        show_sql: true

logging:
  level:
    me.springStudy: DEBUG

jwt:
  header: Authorization
  secret: c29uZ2plb25nLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dA==
  #base64로 인코딩한 것 (songjeong-spirng-boot-security-jwt)
  token-validity-in-seconds: 86400